### ISSUE TITLE
Target class [Spatie\Permission\Middlewares\PermissionMiddleware] does not exist.

### ISSUE THREAD

**Issue by ariawanags** [allphptricks/Laravel-10-roles-and-permissions#1]
i have a problem with error : Target class [Spatie\Permission\Middlewares\PermissionMiddleware] does not exist.

![gambar](https://github.com/allphptricks/Laravel-10-roles-and-permissions/assets/149466505/d9767ee1-056e-47c9-8af6-5d4368786f4e)

**Comment by allphptricks** [comment]
Issue has been fixed, download or clone the updated code.
This tutorial was built with Spatie version 5, all the files are updated with the Spatie Laravel-permission version 6.

**Comment by allphptricks** [comment]
Issue has been fixed
